version: "0.7.0.{build}"
install:
  - ps: Invoke-WebRequest https://github.com/kfl/mosml/releases/download/ver-2.10.1/mosml-setup-2.10.1.exe -OutFile mosml-setup.exe
  - cmd: mosml-setup.exe /VERYSILENT /SUPPRESSMSGBOXES
build_script:
  - cmd: build.cmd /batch /package
test_script:
  - cmd: initool.exe v
artifacts:
  - path: '*.zip'
