version: "0.9.0.{build}"
install:
  - cmd: mkdir c:\mosml
  - ps: Invoke-WebRequest "https://bintray.com/dbohdan/mosml/download_file?file_path=mosml-2.10.1-win32-bin.7z" -OutFile c:\mosml\mosml.7z
  - cmd: pushd c:\mosml & 7z x mosml.7z & popd
build_script:
  - cmd: build.cmd /batch /package
test_script:
  - cmd: initool.exe v
artifacts:
  - path: '*.zip'
deploy:
  - provider: BinTray
    username: dbohdan
    api_key:
      secure: ozw96x1eb8jSUjZWB3NtAeExwJJh7ELyI/mQed79YG6wRtXKps3D4Efr34b8RQDJ
    subject: dbohdan
    repo: initool
    package: initool-win32-bin
    publish: true
